version: '3.8'

services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    ports:
      - "8080:3000"
    volumes:
      - ~/.ssh/wetty_key:/wetty_key:ro
    command: >
      --ssh-host=192.168.1.51
      --ssh-user=vedansh
      --ssh-key=/wetty_key
      --base=/