version: '3.8'

services:
  wetty:
    image: wettyoss/wetty
    network_mode: host
    volumes:
      - ~/.ssh/wetty_key:/wetty_key:ro
    command: >
      --port 8085
      --ssh-host 127.0.0.1
      --ssh-user vedansh
      --ssh-key /wetty_key
    restart: always
